### ISSUE TITLE
Demo application link is dead?

### ISSUE THREAD

**Issue by cogburnd02** [shekhargulati/image-resolver#3]
When I click on the 'demo application' link, it 404's.

**Comment by shekhargulati** [comment]
I deleted the application. Inside the `demo` folder you have the app code. You can deploy it yourself on Heroku.

**Comment by cogburnd02** [comment]
Yeah that's cool, I just thought you should remove the reference to it in the readme which you've apparently already done, so AFAICT this issue is solved.
